---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: yes
      callbacks_enabled: timer, profile_tasks, yaml
      display_failed_stderr: true
      fact_caching: jsonfile
      fact_caching_connection: '/tmp'
      host_key_checking: false
      remote_tmp: '/tmp/.ansible-${USER}/tmp'
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
      ssh_args: '-o ControlMaster=auto -o ControlPersist=1800s -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey'
    diff:
      always: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
